In VS Code, create a folder for your project (e.g., k8s-manifests).

Inside it, create a file → nginx-sidecar-pod.yaml.

 kubectl apply -f nginx-sidecar-pod.yaml

 kubectl get pods

Paste your YAML (like the Deployment I shared). Example:

apiVersion: v1
kind: Pod
metadata:
  name: nginx-sidecar-pod
  labels:
    app: nginx-sidecar
spec:
  containers:
  # Main Nginx container
  - name: nginx-container
    image: nginx:alpine  # Use alpine variant (smaller)
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx

  # Sidecar container
  - name: log-sidecar
    image: busybox:musl  # Use musl variant
    command: ['sh', '-c', 'echo "Waiting for logs..." && sleep 3600']
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx

  volumes:
  - name: shared-logs
    emptyDir: {}

